### PR TITLE
Add firmware reset, up, and version to dpu-tools

### PR DESCRIPTION
**Pull request by SamD2021**
This PR introduces new commands to manage IPU firmware, including:

Firmware Reset: Reset firmware versions.
Firmware Upgrade: Upgrade the firmware using specific version flags.
Firmware Version: Query the current firmware version.
Additionally, it consolidates shared logic into a new common module for reusability and implements a fwutils-based module to interact with the firmware.

### CODE REVIEW

**Comment by bn222** [comment]
Can you create a uniform way to handle all DPUs? Some high level commands that branch into the right tool for the right DPU that you detect

**Comment by SamD2021** [comment]
Hi Balazs, would you want the changes make a uniform way to handle all dpus in a seperate pr or would you want it here?
Sal and I were thinking that to do that it would be useful to reorganize the tools to build from the same dockerfile since we want to unify them under the dpu-tools script.

**Comment by bn222** [comment]
Agreed. Let's get this feature PR in, and then create a refactoring PR. 

Here are my thoughts when I ran throught this as I was working on it: you will have a command to list all DPUs (similar to what I've added for the IPU). Then, since the console command for the IPU is a bit tricky, you will have a mandatory arg: acc/imc. You won't need that for the Marvell.

Also, please make your scripts work outside of the container too (write/clean the config file for minicom before/after as I'm doing for the IPU). iow: running in a container should be detail, not a requirement.

If you fix the style check errors, I will merge pr 25.

@SalDaniele looping in

**Comment by SamD2021** [comment]
Just fixed the style errors, It should be passing the check now!

**Comment by SalDaniele** [comment]
LGTM

**Comment by SalDaniele** [comment]
@bn222 This is all set to merge.

@SamD2021 will follow up with the refactor to consolidate the tools

**Pull request merged**
